#!/usr/bin/env bash
#
# Sets the Basic Auth credential for the memorial upload admin area (/admin/).
# Only a SHA-256 digest of the base64 "user:password" token is written to disk, never
# the password itself.
#
# Writes terraform/auth.auto.tfvars (loaded automatically, git-ignored). Your other
# settings stay in terraform/terraform.tfvars. Apply with:
#   terraform -chdir=terraform apply

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tfvars="$script_dir/terraform/auth.auto.tfvars"

die() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

command -v openssl >/dev/null || die "openssl not found."
command -v shasum >/dev/null || die "shasum not found."

read -r -p "Username: " username
[[ -n "$username" ]] || die "Username must not be empty."
[[ "$username" != *:* ]] || die "Username must not contain a colon (RFC 7617)."

printf 'Tip: generate a strong password with  openssl rand -base64 24\n'
read -r -s -p "Password: " password
printf '\n'
read -r -s -p "Confirm password: " confirm
printf '\n'

[[ -n "$password" ]] || die "Password must not be empty."
[[ "$password" == "$confirm" ]] || die "Passwords do not match."
(( ${#password} >= 12 )) || die "Use at least 12 characters — this is the only thing guarding the uploads."

digest="$(printf '%s' "$username:$password" | openssl base64 -A | shasum -a 256 | cut -d' ' -f1)"
unset password confirm

umask 077
cat > "$tfvars" <<EOF
# Generated by set-password.sh — do not edit, do not commit.
# sha256 of base64("$username:<password>")
credential_sha256 = "$digest"
EOF

printf '\nWrote %s\n' "$tfvars"
printf 'Next: terraform -chdir=%s/terraform apply\n' "$script_dir"
printf 'Store the password in your keychain — it is not recoverable from here.\n'
